Repository ddeboer/imap, pull requests merged in 2018-03, with the labels that each got.

#312 Allow empty port
  src/Server.php
  tests/ServerTest.php
Labels: enhancement

#320 Lazy load Message
  src/Message.php
  src/Message/AbstractPart.php
  src/Message/EmbeddedMessage.php
  tests/MailboxTest.php
  tests/MessageTest.php
Labels: enhancement

#322 imap_mime_header_decode may return false
  src/Message/Parameters.php
  tests/MessageTest.php
  tests/fixtures/imap_mime_header_decode_returns_false.eml
Labels: bug

#325 Add entry in README about Mailbox::addMessage
  README.md
Labels: documentation

#324 base64_decode may return false in PHP < 7.1
  src/Message/AbstractPart.php
  tests/MessageTest.php
  tests/fixtures/boolean_decoded_content.eml
Labels: bug

#328 ImapResource: cache last opened mailbox
  src/Connection.php
  src/ImapResource.php
  src/ImapResourceInterface.php
Labels: enhancement
